apps/studentmonapp/urls.py
from django.conf.urls.defaults import *
from django.views.generic import DetailView
from studentmonapp.models import MonitorEvent, MonitorIssue

urlpatterns = patterns('studentmonapp.views',
                        (r'^admin/createuserschedule/$','createuserschedule'),
                       url(r'^user/$','userhome',name="userhome"),
                       url(r'^report/(?P<report_id>\d+)/$', 'monitor_report_detail', name='monitor_report_detail_view'),
                       url(r'^monitorhours/(?P<pk>\d+)/$',
                        DetailView.as_view( model=MonitorEvent,
                                            template_name='studentmonapp/monitor_event_detail.html',
                                            context_object_name='event',
                                            ),
                           name='monitor_event_detail_view',
                        ),
                       url(r'^monitorissue/(?P<pk>\d+)/$',
                           'monitor_issue_view',
                           name='monitor_issue_detail_view',
                        ),
                       )

''' DetailView.as_view( model=MonitorIssue,
                                            template_name='studentmonapp/monitor_issue_detail.html',
                                            context_object_name='issue',
                                            ),'''

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template

from django.views.generic import ListView
from profiles.models import Profile
from django.contrib import admin
admin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer


handler500 = "pinax.views.server_error"

'''url(r"^$", ListView.as_view(
                queryset=Profile.objects.all(),
                context_object_name='profiles',
                template_name='homepage.html'),
        name="home"),'''

urlpatterns = patterns("",
    url(r"^$",'studentmonapp.views.home',name="home"),
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^admin/", include(admin.site.urls)),
    url(r"^about/", include("about.urls")),
    url(r"^account/", include("pinax.apps.account.urls")),
    url(r"^openid/", include(PinaxConsumer().urls)),
    url(r"^profiles/", include("idios.urls")),
    url(r"^notices/", include("notification.urls")),
    url(r"^announcements/", include("announcements.urls")),
    url(r"^studentmonitors/",include("studentmonapp.urls")),
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        url(r"", include("staticfiles.urls")),
    )

apps/studentmonapp/models.py
from django.db import models
from swingtime.models import Occurrence, OccurrenceManager, Event
from dateutil import rrule
from django.core.urlresolvers import reverse
from datetime import datetime
from django.conf import settings
from django.forms.models import inlineformset_factory
from django.db import models


#for signals
from django.db.models.signals import post_save
from django.dispatch import receiver


# Create your models here.
class MonitorReport(Occurrence):
    """
    """
    FUTUREEVENT = 'FE'
    ONTIME  = 'OK'
    COVERED = 'CO'
    LATE = 'LT'
    MISSED = 'MS'

    STATUS_CHOICES = (
        ('FE', 'Future duty'),
        ('OK', 'Signed in on time'),
        ('CO', 'Covered by another person'),
        ('LT', 'Signed in late'),
        ('MS', 'Monitor missed hours')
        )
    status = models.CharField(max_length=2, choices=STATUS_CHOICES,default=STATUS_CHOICES[0][0])
    signed_time = models.DateTimeField('Date Signed In',null=True, blank=True, default=None)
    user = models.ForeignKey('profiles.Profile', null=True, blank=True, default=None,related_name='reports')
    cover_reason = models.TextField(max_length=250)
    #getting the manager from the superclass
    objects = OccurrenceManager()


    def get_responsible_monitor(self):
        return self.event_type.profile

    def is_on_time_now (self, currenttime):

        print "IS ON TIME: called with %s" % (currenttime)
        
        late_enough = (currenttime > (self.end_time - settings.STUDENTM_SIGNIN_BEFORE_DELTA))
        print "IS ON TIME: late enough: %s" % (late_enough)
        
        on_time =  ((currenttime < (self.end_time + settings.STUDENTM_SIGNIN_AFTER_DELTA)) and late_enough)
        
        print "IS ON TIME: on_time: %s" % (on_time)
        
        return on_time, late_enough

    def is_not_attempting_cover(self, profile):
        return (self.get_responsible_monitor() == profile)

    def can_report(self, profile, currenttime):
        #three cases
        #the person is the right person and they are signing in on time
        #the person is right but signing in late
        #the time is right and another person is covering
        #first going to check the time
        print "CAN REPORT: called"
        if not(self.status == self.FUTUREEVENT or self.status == self.MISSED):
            print "CAN_REPORT: not a future event or missed"
            return False
        timeOK, lateEnough = self.is_on_time_now(currenttime)
        
        personOK = self.is_not_attempting_cover(profile)
        
        return (timeOK or (personOK and lateEnough))

    def get_issue_form(self,post_data=None):
        
        IssueFormSet = inlineformset_factory(MonitorReport,MonitorIssue,
                                             fields=('severity','description','attempted_troubleshooting','solved'),
                                             extra=1,
                                             can_delete=False)
        if post_data:
            return IssueFormSet(post_data,instance=self,prefix='issues')
        return IssueFormSet(instance=self, prefix='issues')
        

    

    def __unicode__(self):
        mon = self.get_responsible_monitor()
        coverstring = mon.name
        if (self.status ==  self.COVERED):
            coverstring = "%s covered for %s" % (self.user.name, mon.name)

        return "%s, STATUS: %s, MONITOR %s," % (self.start_time.date(), self.status, coverstring)


    #@models.permalink
    def get_absolute_url(self):
        return reverse('monitor_report_detail_view', args = [self.id])

class MonitorIssue(models.Model):
    EMERGENCY = 1
    HIGHP  = 2
    DISTRUPTIVE = 3
    WANT = 4

    SEVERITY_CHOICES = (
        (EMERGENCY, 'Emergency - Needs to be fix immediatly for safety or function of lab.'),
        (HIGHP, 'High Priority - Needs to be fixed soon for the lab to be working at full capacity.'),
        (DISTRUPTIVE, 'Distruptive - Would be good to fix soon; an annoyance.'),
        (WANT, 'Want - Something that isnt keeping students from learning or something that is a suggested feature.'),
        )
    NOTSOLVED = 0
    SOLVED = 1
    NA = 2

    SOLVED_CHOICES = (
        (NOTSOLVED, 'Not Solved'),
        (SOLVED, 'SOLVED!'),
        (NA, 'No longer applicable'),
        )
    monitor_report = models.ForeignKey(MonitorReport, blank=True, null=True, default=None, related_name='issues')
    severity = models.PositiveSmallIntegerField(max_length=1, choices=SEVERITY_CHOICES,default=SEVERITY_CHOICES[0][0])
    time_discovered = models.DateTimeField('Date issue discovered')
    date_solved = models.DateTimeField('Date issue solved', blank=True, null=True, default=None)
    user = models.ForeignKey('profiles.Profile')
    description = models.TextField(max_length=500)
    attempted_troubleshooting = models.TextField(max_length=500)
    solved = models.SmallIntegerField(max_length=1, choices=SOLVED_CHOICES,default=SOLVED_CHOICES[0][0]) 
    def __unicode__(self):
        """
        """
        return "%s, SOLVED? %s" % (self.description, self.solved)
    def get_absolute_url(self):
        return reverse('monitor_issue_detail_view', args=[self.id])
    #@models.permalink
    #def get_absolute_url(self):
    #    return('monitor_event_detail',[str(self.id)])

# proxy class for event type to override add event
class MonitorEvent(Event):
    class Meta:
        proxy = True

    def get_absolute_url(self):
        return reverse('monitor_event_detail_view', args=[self.id])
    def reports(self):
        occu = self.occurrence_set.all()
        reports = []
        for o in occu:
            try:
                report = o.monitorreport
                reports.append(report)
            except MonitorReport.DoesNotExist:
                print "Not a monitor report"
        return reports

    def add_occurrences(self, start_time, end_time, **rrule_params):
        #COPIED FROM SWINGTIME MODELS, EVENT, but occurence_Set.create changed to more explicit making of monitor reports.
           '''
        Add one or more occurences to the event using a comparable API to 
        ``dateutil.rrule``. 
        
        If ``rrule_params`` does not contain a ``freq``, one will be defaulted
        to ``rrule.DAILY``.
        
        Because ``rrule.rrule`` returns an iterator that can essentially be
        unbounded, we need to slightly alter the expected behavior here in order
        to enforce a finite number of occurrence creation.
        
        If both ``count`` and ``until`` entries are missing from ``rrule_params``,
        only a single ``Occurrence`` instance will be created using the exact
        ``start_time`` and ``end_time`` values.
        '''
           print "MonitorEvent: add_occurences called"
           rrule_params.setdefault('freq', rrule.DAILY)
           
           if 'count' not in rrule_params and 'until' not in rrule_params:
                mr = MonitorReport(start_time=start_time, end_time=end_time)
                mr.save(force_insert=True)
           else:
                delta = end_time - start_time
                for ev in rrule.rrule(dtstart=start_time, **rrule_params):
                    mr = MonitorReport(event=self,start_time=ev, end_time=ev + delta)
                    mr.save(force_insert=True)


#a signal that updates the user's score whenever a monitor report is changed
def update_user_score(sender, instance, created, **kwargs):
    if not(created):
        instance.user.calc_score()
        print "Score Calculated"

post_save.connect(update_user_score,sender=MonitorReport,dispatch_uid="update_score")

apps/studentmonapp/forms.py
from swingtime.forms import MultipleOccurrenceForm
from studentmonapp.models import MonitorEvent, MonitorReport, MonitorIssue
from django.forms import ModelForm
from django.forms.models import modelformset_factory

class IssueUpdateForm(ModelForm):
    class Meta:
        model = MonitorIssue
        exclude = ('monitor_report','time_discovered','date_solved','user')

class CheckInForm(ModelForm):
    """
    """
    class Meta:
        model = MonitorReport
        exclude = ('status','signed_time','user','start_time','end_time','event','notes',)
    def __init__(self,*args,**kwargs):
        """
        """
        nocover = kwargs.pop('nocover',None)
        super(CheckInForm,self).__init__(*args, **kwargs)
        if nocover:
            del self.fields['cover_reason']

class MultipleReportFormException(Exception):
    pass


class MultipleReportForm(MultipleOccurrenceForm):
    """
    """
    ###copied from multipleoccurenceform
    def save(self, event):
        print "MultipleReportForm: save called"
        if self.cleaned_data['repeats'] == 'no':
            params = {}
        else:
            params = self._build_rrule_params()
        if isinstance(event, MonitorEvent):
            print "MultipleReportForm: is and instance of Monitor event, saving"
            event.add_occurrences(
                self.cleaned_data['start_time'], 
                self.cleaned_data['end_time'],
                **params
                )
        else :
            raise MultipleReportFormException("You are trying to save an event that is not a MonitorEvent using save in the MultipleReportForm")
        return event
    
class ReportEventForm(ModelForm):

    class Meta:
        model = MonitorEvent
        
    #---------------------------------------------------------------------------
    def __init__(self, *args, **kws):
        super(ReportEventForm, self).__init__(*args, **kws)
        self.fields['description'].required = False

def get_issue_form(postdata=None):
    IssueFormSet = modelformset_factory(MonitorIssue, 
                                       fields=('severity','description','attempted_troubleshooting','solved'),
                                       extra=1) 
    if (postdata):
        formset = IssueFormSet(postdata)
    else:
        formset = IssueFormSet(queryset=MonitorIssue.objects.none())
    return formset

templates/studentmonapp/createuserschedule.html
    <h3>Add Event</h3>
    {{ event_form.non_field_errors }}
    {{ recurring_form.non_field_errors }}
    {% if event_form.errors or recurrence_form.errors %}
    <p>Please fix any errors.</p>
    {% endif %}
    <form method="post" action="">
       {% csrf_token %}
    <table>
        <tfoot>
            <tr>
                <td colspan="2"><input type="submit" value="Submit" /></td>
            </tr>
        </tfoot>
        <tbody>
        {% include "studentmonapp/event_form_part.html" %}
        {% include "studentmonapp/recurring_form_part.html" %}
        </tbody>
    </table>
    </form>

templates/studentmonapp/event_form_part.html
        <tr><th>{{ event_form.event_type.label_tag }}</th>
            <td>{{ event_form.event_type.errors }}
                {{ event_form.event_type }}</td></tr>
        <tr><th>{{ event_form.title.label_tag }}</th>
            <td>{{ event_form.title.errors }}
                {{ event_form.title }}</td></tr>
        <tr><th>{{ event_form.description.label_tag }}</th>
            <td>{{ event_form.description }}</td></tr>

templates/studentmonapp/monitor_event_detail.html
{% extends "site_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}Event: {{ event }}{% endblock %}

{% block body %}
    <h4>Event Details</h4>
    <div>
      {{ event.title }}
      <br/>
      {{ event.event_type.profile }}
      <br/>
      {{ event.description }}
      <br/>
    </div>
    <br/>
    <h4>Notes</h4>
    {% with event.notes.all as notes %}
    {% if notes %}
    <ul>
        {% for note in notes %}
        <li>{{ note }}</li>
        {% endfor %}
    </ul>
    {% else %}
    <p>None</p>
    {% endif %}
    {% endwith %}

    <h4>Occurrences</h4>
    Foo value : {{ event.foo }}
    <br/>
    {% if event.reports %}
    <ol>
        {% for o in event.reports %}
        <li>
            <a href="{{ o.get_absolute_url }}">  {{ o }}
                {{ o.start_time|date:"l, F jS, Y P" }} &ndash; 
                {{ o.end_time|date:"l, F jS, Y P" }}</a>
        </li>
        {% endfor %}
    </ol>
    {% else %}
NO OCCUR
    {% endif %}
    
{% endblock body%}

templates/studentmonapp/monitor_issue_detail.html
{% extends "studentmonapp/monitor_report_detail.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}Issue: {{ issue }}{% endblock %}

{% block banner %}

  {% with issue as i %}
	<h3>{{i.description|truncatewords:"10"}}...</h3>
    {% block issue %}
      {{block.super}}
      {%if i.monitor_report %}
	<dd><strong>Monitor Report:</strong> <a href="{{ i.monitor_report.get_absolute_url }}">{{i.monitor_report}}</a>
      {%endif%}
    {% endblock issue %}
{% endwith %}

   {% if issue %}
<h3> Update Issue </h3>
    {% with form as iform %}
    {%block issueform %}
     <form action="" method="post">
       {% csrf_token %}
     <table>

      {{block.super}}
 <tfoot>
   <tr>
     <td colspan="2"><input type="submit" value="Check In" /></td>
   </tr>
 </tfoot>
</table>
</form>

     {%endblock issueform %}

       {%endwith%}
{%endif%}
{% endblock banner%}

templates/studentmonapp/monitor_report_detail.html
{% extends "banner_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}Report for {{occurrence.start_time|date:"M. j P"}} - {{occurrence.end_time|date:"P"}}{% endblock %}


{% block extra_head %}
    {{ block.super }}    

    <script>
      $( document ).ready( function() {
      //set the last form to the last form
      //when they start typing in the last form, generate a new form...we can have a function for that
 
      
      updateLastEl();
      $('#id_issues-TOTAL_FORMS').val($('tbody.single_issue_form_wrapper').length);

      function updateLastEl(){

	if (typeof(lastEl) != "undefined") {

          lastEl.find('textarea').each(function() {
              $(this).unbind('change')
	  });

	}
        last = 'table#issue_forms_wrapper tbody.single_issue_form_wrapper:last'
	lastEl = $(last)
	
        lastEl.find('textarea').each(function() {
	     $(this).unbind()
             $(this).change(function(){
	     cloneMore(last,'issues')
	     });
	});

      }

      function cloneMore(selector, type) {
         var newElement = $(selector).clone(true);
	 var total = $('#id_' + type + '-TOTAL_FORMS').val();//! need to check out what this is
	 newElement.find(':input').each(function() {
	    var name = $(this).attr('name').replace('-' + (total-1) + '-','-' + total + '-');
	    var id = 'id_' + name;
	    $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
	 });

	 newElement.find('label').each(function() {
	    var newFor = $(this).attr('for').replace('-' + (total-1) + '-','-' + total + '-');
	    $(this).attr('for', newFor);
	 });
	 total++;
	 $('#id_' + type + '-TOTAL_FORMS').val(total);
	 $(selector).after(newElement);
	 updateLastEl()
	 
	 
	}

      });


    </script>
{% endblock extra_head %}

{% block banner %}

     {% with occurrence.start_time as st  %}
       {% with occurrence.end_time as et %}
     <h2>{{st|date:"l, F jS "}}</h2>
     <h3>{{st|date:"P"}} - {{et|date:"P"}}</h3>
     {% with occurrence.event as event %}
     
      {{event.event_type.profile|capfirst}}'s Duty
     <br/>
     {% endwith %}
     

	{% endwith %}
	{% endwith %}
	<br/>
	
     <dl>
       <dt>Status:</dt> <dd>{{ occurrence.get_status_display }}</dd>
       
       {% if occurrence.status == occurrence.COVERED %}
         <dt>Cover Reason:</dt>
         <dd>{{ occurrence.cover_reason|default:"None" }}</dd>	   
       {% endif %}
	<h3>Issues</h3>
	<dl>
	{% for i in occurrence.issues.all %}

	<dt><a href="{{i.get_absolute_url}}">{{i.description|truncatewords:"10"}}...</a></dt>
	  {% block issue %}
	<dd><strong>Severity:</strong> {{ i.get_severity_display }} </dd>
	<dd><strong>Time Discovered:</strong> {{ i.time_discovered }} </dd>
	 <dd><strong>User Reporting:</strong> {{ i.user }} </dd>
	 <dd><strong>Description:</strong> {{ i.description }} </dd>
	 <dd><strong>Trouble Shooting:</strong> {{ i.attempted_troubleshooting }} </dd>
	 <dd>
	 {% if i.solved == 1%}
	  <strong>Solved on {{ i.date_solved|default:"unknown date" }}</strong>
	 {% else %}
	  <strong>{{ i.get_solved_display }}</strong>
	 {% endif %}
	 </dd>
	 {% endblock issue %}
	 {% endfor %}

         
     </dl>

     <br/>
     
     {% if form %}
     <form action="" method="post">
       {% csrf_token %}
     <table  id="issue_forms_wrapper">

         <tbody>
              {{ form }}
         </tbody>

{{ inlineform.management_form }}
   {% for iform in inlineform %}

     {%block issueform %}
     <tbody class="single_issue_form_wrapper">

     {%if iform.non_field_errors %}  <tr>{{ iform.non_field_errors }}</tr> {%endif%}
     {% for hidden in iform.hidden_fields %}
       {{ hidden }}
     {% endfor %}

     <tr>
       {{ iform.description.errors }}
       <th><label for="{{iform.description.html_name}}">
	 {{ iform.description.label }}
       </label></th>
       <td>{{ iform.description }}</td>

       {{ iform.attempted_troubleshooting.errors }}
       <th><label for="{{iform.attempted_troubleshooting.html_name}}">
	 {{ iform.attempted_troubleshooting.label }}
       </label></th>
       <td>{{ iform.attempted_troubleshooting }}</td>
     </tr>

     <tr>
       {{ iform.severity.errors }}
       <th><label for="{{iform.severity.html_name}}">
	 {{ iform.severity.label }}
       </label></th>
       <td>{{ iform.severity }}</td>

       {{ iform.solved.errors }}
       <th><label for="{{iform.solved.html_name}}">
	 {{ iform.solved.label }}
       </label></th>
       <td>{{ iform.solved }}</td>
     </tr>

     </tbody> <!--end of the single issue form -->

     {% endblock issueform %}
   {% endfor %}




 <tfoot>
   <tr>
     <td colspan="2"><input type="submit" value="Check In" /></td>
   </tr>
 </tfoot>
</table>
</form>


     {% else %}
       <span class="well">You cannot sign for this report. You are signed in as {{ user.username|capfirst }} and the time is {{ current_time|date:"l, F jS P" }}</span>
     {% endif %}

{% endblock banner %}

{% block bottomrow %} {% endblock bottomrow %}

templates/studentmonapp/recurring_form_part.html
The local version was loaded
        <tr><th>{{ recurrence_form.day.label_tag}}</th>
            <td>{{ recurrence_form.day }}</td></tr>
        <tr><th>{{ recurrence_form.start_time_delta.label_tag }}</th>
            <td>{{ recurrence_form.start_time_delta }}</td></tr>
        <tr><th>{{ recurrence_form.end_time_delta.label_tag }}</th>
            <td>{{ recurrence_form.end_time_delta }}</td></tr>

        <tr><th>{{ recurrence_form.repeats.label_tag }}</th>
            <td>
                {{ recurrence_form.count.errors }}
                <ul>
                    <li><label for="id_repeats_0">
                        <input checked="checked" type="radio" id="id_repeats_0" 
                            value="count" name="repeats" /> A total of</label>
                        {{ recurrence_form.count }} time(s)</li>
                    <li><label for="id_repeats_1">
                        <input type="radio" id="id_repeats_1" value="until" 
                            name="repeats" /> Until </label>
                        {{ recurrence_form.until }}</li>
                </ul></td></tr>

        <tr><th>{{ recurrence_form.freq.label_tag }}</th>
            <td>
                {{ recurrence_form.interval.errors }}
                <div style="float: left">Every {{ recurrence_form.interval }} </div>
                <ul id="recurrence-options">
                    <li><label for="id_freq_0">
                        <input type="radio" id="id_freq_0" 
                            value="3" name="freq" /> Day(s)</label>
                    </li>
                    <li>
                        <label for="id_freq_1">
                            <input checked="checked" type="radio" id="id_freq_1" 
                                value="2" name="freq" /> Week(s):</label>
                        <div class="horizontal form-indent">
                            {{ recurrence_form.week_days }}
                        </div>
                        <br clear="all" />
                    </li>
                    <li>
                        <label for="id_freq_2">
                            <input type="radio" id="id_freq_2" 
                                value="1" name="freq" /> Month(s)</label>
                        <div class="form-indent">
                            <ul>
                                <li>
                                    <label for="id_month_option_0">
                                        <input type="radio" id="id_month_option_0" 
                                            value="on" name="month_option" /> 
                                        On the</label>
                                    {{ recurrence_form.month_ordinal }}
                                    {{ recurrence_form.month_ordinal_day }}
                                </li>
                                <li>
                                    <label for="id_month_option_1">
                                        <input checked="checked" type="radio" 
                                            id="id_month_option_1" value="each" 
                                            name="month_option" /> Each:</label>
                                    <br clear="all" />
                                    <div class="horizontal form-indent">
                                        {{ recurrence_form.each_month_day }}
                                    </div>
                                    <br clear="all" />
                                </li>
                            </ul>
                        </div>
                    </li>
                    <li>
                        <label for="id_freq_3">
                            <input type="radio" id="id_freq_3" 
                                value="0" name="freq" /> Year(s)</label>
                        <div class="form-indent">
                            <div class="horizontal">
                                {{ recurrence_form.year_months}} 
                            </div>
                            <br clear="all" />
                            <div class="form-indent">
                            <label for="id_is_year_month_ordinal">
                                {{ recurrence_form.is_year_month_ordinal }} 
                                On the </label>
                            
                            {{ recurrence_form.year_month_ordinal }}
                            {{ recurrence_form.year_month_ordinal_day }}
                            </div>
                        </div>
                    </li>
                </ul>
            </td>
        </tr>

templates/studentmonapp/userhome.html
{% extends "banner_base.html" %}

{% load i18n %}
{% load ifsetting_tag %}

{% block head_title %}Welcome {{ profile.name }}{% endblock %}

{% block extra_head %}
  {{ block.super }}


    <script>
      $( document ).ready( function() {
      $("#hidden_issue_form").hide();
      $("#issue_toggle_button").click(function(event){
         $("#hidden_issue_form").slideToggle();
      });
 
 
      });
    </script>

{% endblock extra_head %}

{% block banner %}
{%if message %}
<div class="alert-message success">{{message}}</div>

{%endif%}
<h1>Welcome {{ profile.name }}</h1>
<h2>Your next duty</h2>
{% if next_report|length > 0 %}
  {% if can_next_report %}
    <a href="{{ next_report.get_absolute_url }}" class="btn primary large"> Sign In </a>
  {% else %}
    <a href="{{ next_report.get_absolute_url }}"> View </a>
  {%endif%}
{%else%}
  You currently have no future duties
{%endif%}

<h3>Other duties you can check in to </h3>
{%if upcoming_reports%}
  {% for r in upcoming_reports %}
    <a href="{{ r.get_absolute_url }}"> {{ r }} </a>
  {% endfor %}
{%else%}
  No reports to sign in to now
{%endif%}

<h2>Today's Missed Duty Reports</h2>
{% if missed_reports %}
  {% for r in missed_reports_today %}
    <a href="{{ r.get_absolute_url }}"> {{ r }} </a>
  {% endfor %}
{%else%}
    You have not missed any reports today
{%endif%}

<h2> Your Stats </h2>
{{ stats.OnTime }}% On Time ---- {{ stats.Late }}% Late ---- SCORE: {{ stats.Score }}



  <div class="span12 center_parent">
<h3 class="btn large center" id="issue_toggle_button"> Click to report an issue </h3>
</div>

  <div class="span12" id="hidden_issue_form">
<br/>
<br/>

     <form action="" method="post">
       {% csrf_token %}
     <table>

    {{ issue_forms.management_form }}
    {% for iform in issue_forms %}

    {%block issueform %}
           {%if iform.non_field_errors %}  <tr>{{ iform.non_field_errors }}</tr> {%endif%}
     {% for hidden in iform.hidden_fields %}
       {{ hidden }}
     {% endfor %}
     <tr>
       {{ iform.description.errors }}
       <th><label for="{{iform.description.html_name}}">
	 {{ iform.description.label }}
       </label></th>
       <td>{{ iform.description }}</td>

       {{ iform.attempted_troubleshooting.errors }}
       <th><label for="{{iform.attempted_troubleshooting.html_name}}">
	 {{ iform.attempted_troubleshooting.label }}
       </label></th>
       <td>{{ iform.attempted_troubleshooting }}</td>
     </tr>

     <tr>
       {{ iform.severity.errors }}
       <th><label for="{{iform.severity.html_name}}">
	 {{ iform.severity.label }}
       </label></th>
       <td>{{ iform.severity }}</td>

       {{ iform.solved.errors }}
       <th><label for="{{iform.solved.html_name}}">
	 {{ iform.solved.label }}
       </label></th>
       <td>{{ iform.solved }}</td>
     </tr>
     </tr>

    {%endblock issueform%}
    {%endfor%}
 <tfoot>
   <tr>
     <td colspan="2"><input type="submit" value="Add Issue" /></td>
   </tr>
 </tfoot>
</table>
</form>

  </div>


{% endblock banner %}

{%block bottomrow %}


  <div class="span6">
 <h3> All Associated Duties </h3> 
    <ul>
      {% for d in all_duties %}



	<li><a href="{{ d.get_absolute_url }}" class="{{d.status}}_status"> {{ d }} </a></li>
	    
      {% endfor %}
    </ul>
  </div>
  <div class="span6">
    <h3> All Issues You've Reported </h3> 
    <ul>
      {% for r in reported_issues %}
	<li><a href="{{ r.get_absolute_url }}"> {{ r }} </a></li>
      {% endfor %}
    </ul>
  </div>
{% endblock bottomrow%}